/** Mirrors backend PermissionCodes (subset used for routing / UI checks). */
export const PermissionCodes = {
  UserManage: 'USER_MANAGE',
  RoleManage: 'ROLE_MANAGE',
  AuditLogView: 'AUDIT_LOG_VIEW',
  NotificationView: 'NOTIFICATION_VIEW',
  NotificationManage: 'NOTIFICATION_MANAGE',
  SurveyView: 'SURVEY_VIEW',
  SurveyManage: 'SURVEY_MANAGE',
  SurveyApprovalView: 'SURVEY_APPROVAL_VIEW',
  SurveyApprove: 'SURVEY_APPROVE',
  QuestionView: 'QUESTION_VIEW',
  QuestionManage: 'QUESTION_MANAGE',
  TemplateView: 'TEMPLATE_VIEW',
  TemplateManage: 'TEMPLATE_MANAGE',
  ParticipantView: 'PARTICIPANT_VIEW',
  ParticipantManage: 'PARTICIPANT_MANAGE',
  ResponseView: 'RESPONSE_VIEW',
  ResponseManage: 'RESPONSE_MANAGE',
  ReportView: 'REPORT_VIEW',
  ReportExport: 'REPORT_EXPORT',
  RecommendationView: 'RECOMMENDATION_VIEW',
  RecommendationManage: 'RECOMMENDATION_MANAGE',
  ActionPlanView: 'ACTION_PLAN_VIEW',
  ActionPlanManage: 'ACTION_PLAN_MANAGE',
  EmployeeView: 'EMPLOYEE_VIEW',
  EmployeeManage: 'EMPLOYEE_MANAGE',
  PartnerView: 'PARTNER_VIEW',
  PartnerManage: 'PARTNER_MANAGE',
} as const;
